apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: webserver-service
      port:
        number: 80