# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    app: go-site
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-site